favorite/urls.py
""" Contains the urls of the favorite application. """

from . import views
from django.urls import path

app_name = "favorite"

urlpatterns = [
    path("", views.ShowFavorites.as_view(), name="favorites"),
    path("delete/<int:pk>/", views.DeleteFavorites.as_view(), name="delete"),
]

login/urls.py
""" Contains the urls of the login application. """

from django.urls import path
from . import views


urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
    path("logout/", views.user_logout, name="logout"),
    path("account/", views.MyAccount.as_view(), name="account"),
    path("password/", views.PasswordReset.as_view(), name="passreset"),
    path("/", views.PasswordDone.as_view(), name="passdone"),
    path("password_reset/<str:token>", views.NewPassword.as_view(), name="newpass"),
]

nutella/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from login.views import registration


class Home(TemplateView):
    template_name = "index.html"


class Legal(TemplateView):
    template_name = "legal.html"


class Test_bug(TemplateView):
    template_name = "test_bug.html"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", Home.as_view(), name="home"),
    path("login/", include("login.urls")),
    path("registration/", registration, name="registration"),
    path("search/", include("search.urls")),
    path("favorites/", include("favorite.urls")),
    path("legal/", Legal.as_view(), name="legal"),
    path("test_bug/", Test_bug.as_view(), name="test_bug"),
    # path(
    #     "passord/password_reset/", auth_views.PasswordResetView, name="password_reset"
    # ),
    path("", include("django.contrib.auth.urls")),
]

nutella/models.py
""" Database models. """

from django.db import models
from login.models import User


class Category(models.Model):
    name = models.CharField(max_length=400, unique=True)


class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    stores = models.CharField(max_length=200)
    nutriscore = models.CharField(max_length=1)
    url = models.CharField(max_length=300)
    image = models.URLField(default="")
    nutrition = models.URLField(default="")
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)

    def get_six_better_substitutes(self):

        unavaillable_substitutes = list(
            set([favorite.product.id for favorite in Favorite.objects.all()])
        )
        # return the 6 products with the best possible nutriscore
        return Product.objects.filter(category=self.category, nutriscore__lte=self.nutriscore).exclude(pk=self.id).exclude(unavaillable_substitutes).order_by("nutriscore")[:6]


class Favorite(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now_add=True)

nutella/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Pour les amateurs de nutella</title>
    <!-- Favicon-->
    <link rel="icon" href="data:,">
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
        rel="stylesheet" type="text/css" />
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto my-2 my-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'search' %}">Recherche</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account' %}">Mon compte</a></li>
                    
                    <li class="nav-item"><a class="nav-link" href="{% url 'favorite:favorites' %}">Mes aliments</a>
                    </li>
                    
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Déconnexion</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Me connecter</a></li>
                    {% endif %}
                </ul>
                <!-- </div> -->
            </div>
    </nav>
    <!-- Masthead-->

    <header class="masthead">
        {% block head %}
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                    <h2>Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
                    <hr class="divider" />

                </div>
                <div class="col-lg-8 align-self-baseline">
                </div>
            </div>
        </div>
        {% endblock %}
    </header>
    {% block history %}
    <!-- About-->
    <section class="page-section bg-primary" id="about">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-lg-8">
                    <h2 class="text-white text-center mt-0">Colette et Remy</h2>
                    <hr class="divider divider-light" />
                    <p class="text-white-75 mb-4 align-items-center">
                        Pur Beurre est l'initiative de deux amoureux de la gastronomie française, Colette Tatou et Rémy,
                        que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
                        Colette Tatou : "Nous aimons tous manger, surtout en France ! Personnellement, une baguette
                        fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le
                        monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout
                        lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que
                        j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"
                        Remy : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader,
                        surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio
                        (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a
                        demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout
                        de suite où le trouver. L'idée de Pur Beurre était née !!"
                    </p>

                </div>
            </div>
        </div>
        {% endblock %}
    </section>
    {% block contact %}
    <!-- Services-->
    <section class="page-section" id="contact">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">Contactez-nous !</h2>
            <hr class="divider" />
            <div class="row gx-4 gx-lg-5">
                <div class="col-lg-6 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-gem fs-1 text-primary"></i></div>
                        <h3>Maryline Botella</h3>

                    </div>
                </div>
                <div class="col-lg-6 col-md-6 text-center">
                    <div class="mt-5">
                        <div class="mb-2"><i class="bi-laptop fs-1 text-primary"></i></div>
                        <h3 class="h4 mb-2">marybot@free.fr</h3>

                    </div>
                </div>

            </div>
        </div>
    </section>
    {% endblock %}

    <!-- Footer-->
    <footer class="bg-light py-5">
        <div class="container px-4 px-lg-5">
            <div class="small text-center text-muted"><a href="{% url 'legal' %}">Mentions légales</a></div>
        
            
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SimpleLightbox plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>

</html>

nutella/templates/index.html
{% extends 'base.html' %}

nutella/templates/legal.html
{% extends 'base.html' %}
{% block head %}

<p>
    
    Cette application est hébergé sur Heroku. <br>
    Elle est disponible à cette <a href="https://nutellaapp.herokuapp.com/">adresse.</a> <br>
    Le template utilisé est disponible à cette <a href="https://startbootstrap.com/template-overviews/creative/">adresse.</a> <br> 
    La chartre graphique est disponible à cette <a href="https://app.frontify.com/d/6Yy9WFJdtp8j/pur-beurre-style-guide#/introduction/Notre-identité">adresse</a>.
    <a href=""></a>
</p>
{% endblock %}

nutella/templates/test_bug.html
{% extends 'base.html' %}
{% block head %}

<p>

    Page de test<br>
    Test<a href="{% url 'bug' %}">adresse.</a> <br>

</p>
{% endblock %}